---
- name: Run failover-status command on F5
  f5networks.f5_bigip.bigip_command:
    commands: show cm failover-status
  register: f5_status_result
  failed_when: false
  delegate_to: "{{ inventory_hostname }}"
  vars:
    ansible_connection: httpapi

- name: Set combined stdout as result for retries
  ansible.builtin.set_fact:
    stdout: "{{ f5_status_result.stdout }}"
    failed: false
